# Generated by Django 4.0.4 on 2022-06-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=400,unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.page')),
                ('user_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.userdevice')),
            ],
        ),
    ]
