# Generated by Django 4.0.4 on 2022-06-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_pageconfig_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageconfig',
            unique_together=set(),
        ),
    ]
